selector_id: "1"
port: "50051"
coordinator_address: "localhost:50050"
fl_root_path: "../data"
init_files_path: "/initFiles/"
model_file: "model.h5"
agg_checkpoint_file_path: "/fl_agg_checkpoint"
agg_checkpoint_weight_path: "/fl_agg_checkpoint_weight"
round_checkpoint_updates_dir: "/roundFiles/checkpoint_"
round_checkpoint_weight_dir: "/roundFiles/checkpoint_weight_"
chunk_size: 65536 #64 * 1024
post_checkin_reconnection_time: 8000
post_update_reconnection_time: 8000
estimated_waiting_time: 20000