init-files-path: "/initFiles/"
model-file: "model.h5"
agg-checkpoint-file-path: "/fl_agg_checkpoint"
agg-checkpoint-weight-path: "/fl_agg_checkpoint_weight"
round-checkpoint-updates-dir: "/roundFiles/checkpoint_"
round-checkpoint-weight-dir: "/roundFiles/checkpoint_weight_"
chunk-size: 65536 #64 * 1024
post-checkin-reconnection-time: 8000
post-update-reconnection-time: 8000
estimated-waiting-time: 20000
